#
# 服务器 配置
server:
  # 服务器端口
  port: 8002
  # 是否应将X-Forwarded-* 标头应用于HttpRequest（使用 Nginx 后，用户获取用户真实 IP）。
  use-forward-headers: true
  # Tomcat 配置（使用 Nginx 后，用户获取用户真实 IP）
  tomcat:
    # 从中提取远程IP的HTTP标头的名称。 例如，`X-FORWARDED-FOR`。
    remote-ip-header: X-Real-IP
    # 用于覆盖原始端口值的HTTP标头的名称。
    port-header: X-Forwarded-Proto
#
# Spring Boot 配置
spring:
  #
  # Thymeleaf 配置
  thymeleaf:
    # 是否启用模板缓存。
    cache: false
#
